//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unimacs_3000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoatMotion
    {
        public int id { get; set; }
        public double left_engine_value { get; set; }
        public double right_engine_value { get; set; }
        public double rudder_value { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
