//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unimacs_3000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boat
    {
        public string id { get; set; }
        public string name { get; set; }
        public string control_mode { get; set; }
        public Nullable<byte> isActive { get; set; }
    }
}
