//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unimacs_3000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoatMotion
    {
        public int id { get; set; }
        public double LeftEngineValue { get; set; }
        public double RightEngineValue { get; set; }
        public double RudderValue { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
