//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unimacs_3000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorData
    {
        public int id { get; set; }
        public string sensor_name { get; set; }
        public string NMEA_code { get; set; }
        public double sensor_value { get; set; }
        public byte[] timestamp { get; set; }
    }
}
